branches:
  except: release

language: php
php:
  - '5.6'
  - '7.0'

git:
  depth: 3
  
before-script:  
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  
script:
  - phpunit --bootstrap expandFns.php tests/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)