branches:
  except: release

language: php
php:
  - '7.0'

git:
  depth: 3
  
before-script:  
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  
script:
  - phpunit --coverage-clover=coverage.xml --bootstrap expandFns.php tests/phpunit

after_success:
  bash <(curl -s https://codecov.io/bash) -t e6bb38cc-18e6-4153-b2fc-23bcd681ef73