sudo: false
dist: trusty
branches:
  except: release

language: php
before_script:  
  - travis_retry composer self-update
  - composer require mediawiki/oauthclient
    
matrix:
  include:
    - stage: test    
    - php: 7.0
      #script: phpunit --coverage-clover coverage.xml --bootstrap expandFns.php tests/phpunit
      script: echo "Hullo 7.0"
      after_success: bash <(curl -s https://codecov.io/bash)
    - php: 5.6
      #script: phpunit --bootstrap expandFns.php tests/phpunit
      script: echo "Hullo 5.6"
    - stage: deploy
      name: "Update WMFlabs servers"
      before_script: skip
      if: branch = master AND !env(TRAVIS_PULL_REQUEST)
      script: bash <(echo wget -O- https://tools.wmflabs.org/citations/gitpull.php)
      if: branch = development AND !env(TRAVIS_PULL_REQUEST)
      script: bash <(echo wget -O- https://tools.wmflabs.org/citations-dev/gitpull.php)

git:
  depth: 3
  
