sudo: false
dist: trusty
branches:
  except: release

language: php

matrix:
  include:
    - php: 7.0
      script: phpunit --coverage-clover coverage.xml --bootstrap expandFns.php tests/phpunit
    - php: 5.6
      script: phpunit --bootstrap expandFns.php tests/phpunit
    - stage: deploy
      - name: "Generate code coverage report"
        script: bash <(curl -s https://codecov.io/bash)
      - name: "Update WMFlabs servers"
        if: branch = master
        script: bash <(echo wget -O- https://tools.wmflabs.org/citations/gitpull.php)
        if: branch = development
        script: bash <(echo wget -O- https://tools.wmflabs.org/citations-dev/gitpull.php)

git:
  depth: 3

before_script:  
  - travis_retry composer self-update
  - composer require mediawiki/oauthclient
  
