language: php
php:
  - '7.0'
git:
  depth: 3
before-script:
  - phpenv config-rm xdebug.ini
  - composer install
script:
  - phpdbg -qrr phpunit
  - phpunit --bootstrap expandFns.php tests/phpunit/expandFnsTest.php
  - phpunit --bootstrap expandFns.php tests/phpunit/TemplateTest.php
  - phpunit --bootstrap constants.php tests/phpunit/constantsTest.php
  - phpunit --bootstrap Parameter.php tests/phpunit/ParameterTest.php
